# Generated by Django 2.2.27 on 2025-12-20 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'proveedor',
                'verbose_name_plural': 'proveedores',
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='número de factura'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='valor_ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor de ingreso'),
        ),
        migrations.CreateModel(
            name='IngresoInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('numero_factura', models.CharField(blank=True, max_length=255, null=True, verbose_name='número de factura')),
                ('valor_ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='valor de ingreso')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos', to='core.Inventario')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='core.Proveedor')),
            ],
            options={
                'verbose_name': 'ingreso inventario',
                'verbose_name_plural': 'ingresos inventario',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='core.Proveedor', verbose_name='proveedor'),
        ),
    ]
