# Generated by Django 2.2.27 on 2026-02-05 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20251220_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_orden', models.CharField(max_length=100, verbose_name='número de orden')),
                ('codigo', models.CharField(max_length=100, verbose_name='código')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='core.Proveedor')),
            ],
            options={
                'verbose_name': 'programacion',
                'verbose_name_plural': 'programaciones',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionInsumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='core.Inventario')),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='core.Programacion')),
            ],
            options={
                'verbose_name': 'programacion insumo',
                'verbose_name_plural': 'programaciones insumos',
                'ordering': ['-created'],
            },
        ),
    ]
