# Generated by Django 2.2.27 on 2026-02-14 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tercero', models.CharField(max_length=255, verbose_name='nombre tercero')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('ref', models.CharField(blank=True, max_length=255, null=True, verbose_name='ref')),
                ('tela', models.CharField(blank=True, max_length=255, null=True, verbose_name='tela')),
                ('mtrs_enviados', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='mtrs enviados')),
                ('lote', models.CharField(blank=True, max_length=255, null=True, verbose_name='lote')),
                ('orden_produccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='orden de produccion')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='notas')),
                ('tallas', models.TextField(blank=True, null=True, verbose_name='tallas_json')),
                ('total_unidades', models.IntegerField(default=0, verbose_name='total unidades cortadas')),
                ('total_metros_consumidos', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='total metros consumidos')),
                ('mtrs_retazos', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='mtrs de retazos')),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='promedio')),
                ('muestras', models.IntegerField(default=0, verbose_name='muestras')),
                ('faltante_tela', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='faltante de tela')),
                ('consumo_cantidad', models.IntegerField(default=0, verbose_name='consumo cantidad')),
                ('consumo_metros_gastados', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='consumo metros gastados')),
                ('consumo_ancho', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='consumo ancho')),
                ('consumo_largo', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='consumo largo')),
                ('consumo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='consumo promedio')),
                ('sobrante_tela', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sobrante de tela')),
                ('firma_responsable', models.CharField(blank=True, max_length=255, null=True, verbose_name='firma responsable')),
            ],
            options={
                'verbose_name': 'corte',
                'verbose_name_plural': 'cortes',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CorteDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero', models.IntegerField(default=0, verbose_name='corte_num')),
                ('proporcion', models.CharField(blank=True, max_length=100, null=True)),
                ('unidades_cortadas', models.IntegerField(default=0)),
                ('ancho', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('largo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('promedio', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('mtrs_consumidos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.Corte')),
            ],
            options={
                'verbose_name': 'corte detalle',
                'verbose_name_plural': 'cortes detalles',
                'ordering': ['numero'],
            },
        ),
    ]
