# Generated by Django 2.2.27 on 2026-02-24 22:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_corte_cortedetalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_orden', models.CharField(blank=True, max_length=100, null=True, verbose_name='número de orden')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='referencia')),
                ('estado_proceso', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En proceso'), ('FIN', 'Finalizado')], default='PEN', max_length=3, verbose_name='estado del proceso')),
                ('fecha_finalizacion', models.DateField(blank=True, null=True, verbose_name='fecha de finalizacion')),
                ('cortes', models.ManyToManyField(blank=True, related_name='presentaciones', to='core.Corte')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentaciones', to='core.Programacion')),
            ],
            options={
                'verbose_name': 'presentacion',
                'verbose_name_plural': 'presentaciones',
                'ordering': ['-created'],
            },
        ),
    ]
