# Generated by Django 2.2.27 on 2026-03-23 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programaciones', to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de entrega'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='tallas',
            field=models.TextField(blank=True, null=True, verbose_name='tallas_json'),
        ),
    ]
