# Generated by Django 2.2.27 on 2026-03-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20260323_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programacion',
            options={'ordering': ['prioridad', '-created'], 'verbose_name': 'programacion', 'verbose_name_plural': 'programaciones'},
        ),
        migrations.AddField(
            model_name='programacion',
            name='prioridad',
            field=models.IntegerField(default=0, help_text='Número de prioridad para ordenar programaciones activas', verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='orden de compra'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='observaciones'),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='numero_orden',
            field=models.CharField(max_length=100, verbose_name='referencia'),
        ),
    ]
