# Generated by Django 2.2.27 on 2026-03-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20260323_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='corte',
            name='estado',
            field=models.CharField(choices=[('RECIBO', 'Recibo'), ('ESTANTERIA', 'Estanteria'), ('PREPARACION', 'Preparacion'), ('ENSAMBLE', 'Ensamble'), ('FIN_PUNTAS', 'Fin Puntas'), ('PRESILLA', 'Presilla'), ('TERMINADO', 'Terminado')], default='RECIBO', max_length=20, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='corte',
            name='fecha_estado',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de estado'),
        ),
    ]
