# Generated by Django 2.2.27 on 2026-03-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20260324_0014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corte',
            name='ref',
        ),
    ]
