# Generated by Django 2.2.27 on 2026-03-24 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_ref_from_corte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lavanderia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('referencia', models.CharField(max_length=100, verbose_name='referencia')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('numero_remision', models.CharField(max_length=100, verbose_name='número de remisión')),
                ('lavanderia', models.CharField(max_length=255, verbose_name='lavandería')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('tipo', models.CharField(choices=[('SALIDA', 'Salida'), ('RECEPCION', 'Recepción')], default='SALIDA', max_length=20, verbose_name='tipo')),
                ('cantidad_conformes', models.IntegerField(default=0, verbose_name='cantidad conformes')),
                ('cantidad_no_conformes', models.IntegerField(default=0, verbose_name='cantidad no conformes')),
                ('corte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavanderias', to='core.Corte')),
                ('programacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lavanderias', to='core.Programacion')),
            ],
            options={
                'verbose_name': 'lavanderia',
                'verbose_name_plural': 'lavanderias',
                'ordering': ['-created'],
            },
        ),
    ]
