# Generated by Django 2.2.27 on 2026-03-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_lavanderia'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavanderia',
            name='remision_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='core.Lavanderia', verbose_name='remisión de salida'),
        ),
    ]
