# Generated by Django on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_lavanderia_remision_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='contacto'),
        ),
    ]
