# Generated by Django on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_contacto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='documento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='teléfono'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='correo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='dirección'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='observación'),
        ),
    ]
