# Generated by Django 2.2.27 on 2026-08-05 19:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_cliente_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='order_number')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha')),
                ('status', models.CharField(choices=[('ingreso', 'Ingreso'), ('revision', 'Revision'), ('procedimiento', 'Procedimiento'), ('entrega', 'Entrega'), ('cerrada', 'Cerrada')], default='ingreso', max_length=32)),
                ('ingreso', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('revision', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('procedimiento', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('entrega', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_taller', to='core.Cliente')),
            ],
            options={
                'verbose_name': 'orden taller',
                'verbose_name_plural': 'ordenes taller',
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='cortedetalle',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='lavanderia',
            name='corte',
        ),
        migrations.RemoveField(
            model_name='lavanderia',
            name='programacion',
        ),
        migrations.RemoveField(
            model_name='lavanderia',
            name='remision_salida',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='cortes',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='programacion',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='programacioninsumo',
            name='inventario',
        ),
        migrations.RemoveField(
            model_name='programacioninsumo',
            name='programacion',
        ),
        migrations.DeleteModel(
            name='Corte',
        ),
        migrations.DeleteModel(
            name='CorteDetalle',
        ),
        migrations.DeleteModel(
            name='Lavanderia',
        ),
        migrations.DeleteModel(
            name='Presentacion',
        ),
        migrations.DeleteModel(
            name='Programacion',
        ),
        migrations.DeleteModel(
            name='ProgramacionInsumo',
        ),
    ]
